### ISSUE TITLE
Appears to be broken in the latest version of HA.

### ISSUE THREAD

**Issue by glockpete** [vwt12eh8/hass-nature-remo#1]
As title, not technical so not much more i can add.
Would love a fix if you find time! Thx

**Comment by diginatu** [comment]
I'm also experiencing an error during installation, and the error log I have is as follows.
I'll investigate this issue further.

```
2023-12-29 22:38:50.076 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Nature Remo for nature_remo
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/nature_remo/__init__.py", line 56, in async_setup_entry
update_appliance_info()
File "/config/custom_components/nature_remo/__init__.py", line 48, in update_appliance_info
dr.async_get_or_create(
File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 540, in async_get_or_create
device_info_type = _validate_device_info(config_entry, device_info)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 187, in _validate_device_info
raise DeviceInfoError(
homeassistant.helpers.device_registry.DeviceInfoError: Invalid device info {'default_manufacturer': 'NEC', 'default_model': 'NEC LIGHT 001', 'identifiers': {('nature_remo', '***-***-***')}, 'name': 'Living Light', 'via_device': ('nature_remo', '***-***-***')} for 'nature_remo' config entry: device info needs to either describe a device, link to existing device or provide extra information.
```
